config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "restaurants#index"

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Yelp Mvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Bootstrap's CSS %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
    rel="stylesheet" crossorigin="anonymous">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <%# Bootstrap's JS %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>

    <%# Font Awesome %>
    <script src="https://kit.fontawesome.com/b66791e090.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/restaurants/_restaurant_form.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, collection: %w[Chinese Italian Japanese French Belgian], as: :select %>
  <%= f.submit class: "btn btn-success"%>
<% end %>

app/views/restaurants/edit.html.erb
<div class="text-center">
  <div class="card mt-5 w-50" style="margin: 0 auto;">
    <div class="card-header">
      Currently editing <strong><%= @restaurant.name %></strong>
    </div>
    <div class="card-body">
      <%= render 'restaurant_form', restaurant: @restaurant %>
    </div>
  </div>
  <%= link_to 'Back to details', restaurant_path(@restaurant.id), class: 'btn btn-primary mt-5' %>
</div>

app/views/restaurants/index.html.erb
<div class="text-center">
<%# <p>Find me in app/views/restaurants/index.html.erb</p> %>
  <h1 class="mt-5">Restaurants</h1>

  <% if Restaurant.all.empty? %>
    <p class="mt-4">There are currently no registered restaurants!</p>
  <% else %>
    <div class="row mt-3">
      <% @restaurants.each do |restaurant| %>
        <div class="col-3 text-center">
          <div class="card p-4 mt-4">
            <h5 class="card-title"><%= restaurant.name %></h5>
            <p class="card-text"><%= restaurant.category.capitalize %> food</p>
            <%= link_to "See Details", restaurant_path(restaurant), class: 'btn btn-outline-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= link_to 'Add new restaurant', new_restaurant_path, class: 'btn btn-primary mt-5' %>
</div>


<%# <i class="fa-solid fa-trash"></i> %>

app/views/restaurants/new.html.erb
<div class="text-center">
  <div class="card mt-5 w-50" style="margin: 0 auto;">
    <div class="card-header">
      Creating new restaurant
    </div>
    <div class="card-body">
      <%= render 'restaurant_form', restaurant: @restaurant %>
    </div>
  </div>
  <%= link_to 'Back to index', restaurants_path, class: 'btn btn-primary mt-5' %>
</div>

app/views/restaurants/show.html.erb
<div class="text-center">
  <div class="card mt-5 w-50" style="margin: 0 auto;">
    <div class="card-header text-start">
      <%= @restaurant.category.capitalize %> Food
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @restaurant.name %></h5>
      <p class="card-text"><%= @restaurant.address %></p>
      <%= link_to 'Edit restaurant', edit_restaurant_path(@restaurant), class: 'btn btn-sm text-secondary' %>
      <%# <a href="#" class="btn btn-sm text-primary">Write a review</a> %>
      <%= link_to 'Write a review', new_restaurant_review_path(@restaurant), class: "btn btn-sm text-primary" %>
      <%= link_to "Delete restaurant", restaurant_path(@restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-sm text-danger'%>
    </div>
  </div>

  <%# <hr> %>

  <h5 class="mt-5">Reviews</h5>
  <% if @restaurant.reviews.empty? %>
    <p class="mt-4">There are currently no reviews!</p>
  <% else %>
    <div class="row overflow-auto flex-nowrap ">
      <% @restaurant.reviews.each do |review| %>
        <div class="card col-3 m-3">
          <div class="card-body">
            <p class="card-text">
              <% review.rating.to_i.times do %>
                <i class="fa-solid fa-star text-warning"></i>
              <% end %>
              <% (5 - review.rating.to_i).times do %>
                <i class="fa-solid fa-star text-secondary"></i>
              <% end %>
            </p>
            <p class="card-text">
              <%= review.content %>
            </p>
          </div>
          <div class="card-footer bg-white">
            <%= link_to "Delete review", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-sm text-danger'%>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>


  <%= link_to 'Back to index', restaurants_path, class: 'btn btn-primary mt-5' %>
</div>

app/views/reviews/new.html.erb
<div class="text-center">
  <div class="card mt-5 w-50" style="margin: 0 auto;">
    <div class="card-header">
      Write a review for <strong><%= @restaurant.name %></strong>
    </div>
    <div class="card-body">
      <%= simple_form_for [@restaurant, @review] do |f|  %>
        <%= f.input :content %>
        <%= f.input :rating, collection: (0..5), selected: 0 %>
        <%= f.submit class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
  <%= link_to 'Back to details', restaurant_path(@restaurant.id), class: 'btn btn-primary mt-5' %>
</div>